"""fix

Revision ID: 19796a53d7ad
Revises: 
Create Date: 2025-11-27 20:20:34.168283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19796a53d7ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyurtma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_buyurtma_customer', 'customer', ['customer'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('workplace',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('workplace',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('buyurtma', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buyurtma_customer', type_='foreignkey')
        batch_op.drop_column('customer')

    # ### end Alembic commands ###
